### ISSUE TITLE
authnet support for 4.4?

### ISSUE THREAD

**Issue by jmcclelland** [sgladstone/com.pogstone.paymentprocessorhelper#1]
Does this extension work with CiviCRM 4.4?

I saw this in the authorize class:

  require_once('utils/Entitlement.php');
  $tmpEntitlement = new Entitlement();

  if($tmpEntitlement->isRunningCiviCRM_4_3() ){
    // Do nothing. CRON job will process the data into contributions. 
  }else{
        print "<br><br>ERROR: This code is only meant for CiviCRM 4.3.x";
 ....

It seems to suggest that it only checks if you are running 4.3, not if you are running a version greater than 4.3... but I'm not sure because I'm also not sure where the utils/Entitlement.php class comes from or what happens if it's not available.

Also - is there any way to extend the existing CRM_Core_Payment_AuthorizeNetIPN class rather than replace it? Since you are replacing it you have to always have the most up to date version to ensure you get all the latest bug fixes.

**Comment by sgladstone** [comment]
This extension works with CiviCRM 4.4.x and 4.5.5   I have not investigated a way to extend CRM_Core_Payment_AuthorizeNetIPN in an extension. Since the only logic in the core version of that file relates to turning a IPN message into a contribution, I do not worry about updating that logic (based  on fixes to core) since the intention of this extension is to bypass the core handling of IPN messages. 

Personally I think any payment processor-related logic should be stripped from core and live only in various extensions.
